name: Run Tests & Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=yrs_commons --cov-report=xml
#
#      - name: Upload coverage to Coveralls
#        uses: coverallsapp/github-action@v2
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
